### ISSUE TITLE
統一した方が見やすい

### ISSUE THREAD

**Issue by c0a21088** [c0a21124f8/ProjExD#16]
https://github.com/c0a21124f8/ProjExD/blob/f4a8954253cfefad83c2644ae4f7ff348a5620bc/ex04/dodge_bomb.py#L41
マウス操作など非常に良かったと思います。
ここの部分は下の部分で[K_○○]というように呼び出しているので、統一した方が見やすい気がします

**Comment by c0a21124f8** [comment]
ありがとうな...
お前の意志は俺が受け継ぐ...
だから安心して眠ってくれ友よ...
