### ISSUE TITLE
whileよりforがおすすめ

### ISSUE THREAD

**Issue by c0a2110056** [c0a21124f8/ProjExD#4]
https://github.com/c0a21124f8/ProjExD/blob/06084a19e51ae481d1f3a3f6ce1b956f915113f0/ex01/alphabet.py#L21
繰り返し回数はグローバル変数として定義していいからそっちの方が楽じゃないかなたぶん

**Comment by c0a21124f8** [comment]
多分であやふやなことを言わずに具体的な例を出してくれるとありがたいです。
